# Generated by Django 4.2.2 on 2023-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageprediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netrual', models.CharField(blank=True, max_length=50, null=True)),
                ('sexy', models.CharField(blank=True, max_length=50, null=True)),
                ('drawing', models.CharField(blank=True, max_length=50, null=True)),
                ('porn', models.CharField(blank=True, max_length=50, null=True)),
                ('henai', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
