# Generated by Django 4.2.2 on 2023-06-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageprediction',
            old_name='netrual',
            new_name='neutral',
        ),
    ]
