# Generated by Django 4.2.2 on 2023-06-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_netrual_imageprediction_neutral'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprediction',
            name='upload',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
