# Generated by Django 4.2.2 on 2023-06-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_imageprediction_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageprediction',
            old_name='upload',
            new_name='image',
        ),
    ]
