# Generated by Django 4.2.2 on 2023-06-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_upload_imageprediction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprediction',
            name='drawing',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageprediction',
            name='henai',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageprediction',
            name='neutral',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageprediction',
            name='porn',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageprediction',
            name='sexy',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
